service: serverless-dynamo-basic-operations

plugins:
  - serverless-dynamodb-local

custom:
  myStage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      ENTITIES_DYNAMODB_TABLE: MoD-entities-dev
    prod:
      ENTITIES_DYNAMODB_TABLE: MoD-entities-prod

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: us-east-1
  environment: ${self:custom.settings.${self:custom.myStage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.ENTITIES_DYNAMODB_TABLE}"

functions:
  saveItem:
    handler: handler.saveItem
    events:
      - http:
          path: item
          method: post
  getItem:
    handler: handler.getItem
    events:
      - http:
          path: item/{itemId}
          method: get
  deleteItem:
    handler: handler.deleteItem
    events:
        - http:
            path: item/{itemId}
            method: delete
  updateItem:
    handler: handler.updateItem
    events:
      - http:
          path: item/{itemId}
          method: put

resources:
  Resources:
    MudTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "itemId"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "itemId"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.${self:custom.myStage}.ENTITIES_DYNAMODB_TABLE}
        # StreamSpecification:
        #   StreamViewType: NEW_IMAGE
